# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class ImageResizerFn:
        name: str
        type: str
        url: str
    class KIT_API_KEY:
        type: str
        value: str
    class KIT_API_SECRET:
        type: str
        value: str
    class STRIPE_SECRET_KEY:
        type: str
        value: str
    class STRIPE_WEBHOOK_SECRET:
        type: str
        value: str
    class Web:
        type: str
        url: str

